// <auto-generated />
using DTC_CRUD_MVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DTC_CRUD_MVC.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DTC_CRUD_MVC.Models.Karyawan", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("gender")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salaryid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("salaryid");

                    b.ToTable("Karyawans");
                });

            modelBuilder.Entity("DTC_CRUD_MVC.Models.Late", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idperson")
                        .HasColumnType("int");

                    b.Property<float>("late")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.HasIndex("idperson");

                    b.ToTable("Lates");
                });

            modelBuilder.Entity("DTC_CRUD_MVC.Models.Salary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("SalaryNominal")
                        .HasColumnType("real");

                    b.Property<string>("SalaryType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaryId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("DTC_CRUD_MVC.Models.Karyawan", b =>
                {
                    b.HasOne("DTC_CRUD_MVC.Models.Salary", "Salary")
                        .WithMany()
                        .HasForeignKey("salaryid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DTC_CRUD_MVC.Models.Late", b =>
                {
                    b.HasOne("DTC_CRUD_MVC.Models.Karyawan", "karyawan")
                        .WithMany()
                        .HasForeignKey("idperson")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
